Get ready for your U-Guide Hunt, can your dog mark?
Intro text
By: Mark Staloch
UGUIDE South Dakota Pheasant Hunting - Jan. 15, 2010

The Importance of Your Retriever Being Able to Mark Birds Properly

Just the mention of a SD pheasant hunt is enough to send the mind of a bird hunter racing with thoughts of an almost fantasy-like experience. It will fill an adult with a childlike giddiness. The experiences of a South Dakota hunt may range from staying at the farmhouse of a buddy's grandparent to making reservations at a high end lodge. Obviously if you are reading this, you are on the U-Guide website and are either thinking about or have already booked a hunt with U-Guide. Well you are making a good choice. By giving you an opportunity to hunt truly wild birds, U-Guide camps are some of the most unique operations in the state of South Dakota. It is really what an out of state trip is all about: hunting birds in a way and quantity that is not available in your home state.

I was given the opportunity to have my own U-Guide experience this December just before Christmas. It was an experience that was better than any pheasant hunt that I had ever been on. I was able to hunt a camp that had been hunted three days a week every week for ten weeks prior to my hunt. Even with this hunting pressure, there were still more birds than could be counted with plenty of roosters.

So many times when preparing for a trip, hunters think about getting time off from work or getting some new equipment such as boots or a jacket. To me, your most important equipment is also your best buddy; your dog. Since I am a dog trainer, I am going to discuss what your dog should know in preparation for your hunt. Regardless of the breed, the most important thing it needs to know are basic obedience commands. When I say that a dog knows the command that does not mean that it knows what it means and does it sometimes. No, I mean when the dog is given a command, it responds to it as soon as the command is given. There are going to be a lot of people shooting and a lot of birds which can lead to confusing situations for the dog. Keeping the dog under control keeps the hunt going smoothly. Every dog needs to be able to be stopped, to come back to you and to heel. The heel command is often a command that is not worked on enough but is a real asset to the hunt. It is very nice to have your dog heel nicely beside you as you walk through the field on your way to set up for the hunt. The flushing breeds (spaniels, labs, goldens, etc.) should really work on a few different things. Of course you should work on quartering and tracking. Really one of the most important things to work on with the dog is something that upland hunters almost never work on; marking. Many people don't even really know what it is or how important it is. Marking is the ability of the dog to see the bird fall, know exactly where it is and take the most direct route to the bird whether it falls 30 yards or 300 yards away. Once the dog has used its eyes to get itself to the area of the fall, it can then use its nose to do the rest of the job. This is much better than having a person walk the dog over to the area of the fall which can disturb the scent in the fall area. This skill is very important for your dog to have during your U-Guide experience. The number of birds you see and the amount of bird scent is so thick that your dog needs to get to the area of the fall as fast and efficiently as possible to have the best chance to recover the bird. This is especially important if the bird is only crippled.

A U-Guide hunt is much different from hunting in other states, a game farm or even other South Dakota hunts that I have been on. Many times there are so many birds using the cover on a daily or even hourly basis that it creates a different type of scenting difficulty for the dogs. This makes it very important that the dogs can get on a cripple's trail asap. I have been amazed at the visual abilities of a good retriever. Even if there are dozens of birds in the air, a dog can be trained to watch the one that drops and be sent for it. Having a steady dog sitting beside you while you are blocking at the end of a field that can be sent on command to retrieve a downed bird is essential. This allows you to stay in position and continue shooting at passing birds instead of going to look for the bird yourself. Improving your dog's marking abilities is certainly one of the things that most upland hunters overlook, but it is one of the easiest ways to increase your dog's usefulness as a hunting tool. Having a dog that can make efficient retrieves helps create a smooth hunt putting more birds into your game pouch. The three greatest things to talk about in the hours days and weeks after a bird hunt are: the number of birds seen, great shots (made and missed) and great retrieves. When you go to a U-Guide camp the birds will be there. Make sure that your dog has the skills it takes to find the ones you hit.

Mark Staloch Norse Retrievers 715 533-2339